"""empty message

Revision ID: 230b19316e5a
Revises: 92c4f2781816
Create Date: 2021-04-13 21:06:19.072124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '230b19316e5a'
down_revision = '92c4f2781816'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character', sa.Column('hair_color', sa.String(length=25), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('character', 'hair_color')
    # ### end Alembic commands ###
