"""empty message

Revision ID: 3423a23c0b08
Revises: 9428fbb637ee
Create Date: 2021-04-14 17:01:42.676270

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3423a23c0b08'
down_revision = '9428fbb637ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('planet', 'diameter')
    op.drop_column('planet', 'orbital_period')
    op.drop_column('planet', 'population')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planet', sa.Column('population', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('planet', sa.Column('orbital_period', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('planet', sa.Column('diameter', mysql.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
