"""empty message

Revision ID: 56be1d5922ff
Revises: 3423a23c0b08
Create Date: 2021-04-14 17:03:40.837839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56be1d5922ff'
down_revision = '3423a23c0b08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planet', sa.Column('diameter', sa.String(length=25), nullable=True))
    op.add_column('planet', sa.Column('orbital_period', sa.String(length=25), nullable=True))
    op.add_column('planet', sa.Column('population', sa.String(length=25), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('planet', 'population')
    op.drop_column('planet', 'orbital_period')
    op.drop_column('planet', 'diameter')
    # ### end Alembic commands ###
