"""empty message

Revision ID: 77bcd95691d3
Revises: abf5884431f9
Create Date: 2021-04-12 21:11:13.505894

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '77bcd95691d3'
down_revision = 'abf5884431f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character', sa.Column('eye_color', sa.String(length=25), nullable=True))
    op.add_column('character', sa.Column('hair_color', sa.Integer(), nullable=True))
    op.drop_column('character', 'birthYear')
    op.drop_column('character', 'description')
    op.drop_column('character', 'age')
    op.drop_column('planet', 'description')
    op.drop_column('planet', 'climate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planet', sa.Column('climate', mysql.VARCHAR(length=25), nullable=True))
    op.add_column('planet', sa.Column('description', mysql.VARCHAR(length=300), nullable=True))
    op.add_column('character', sa.Column('age', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('character', sa.Column('description', mysql.VARCHAR(length=300), nullable=True))
    op.add_column('character', sa.Column('birthYear', mysql.VARCHAR(length=25), nullable=True))
    op.drop_column('character', 'hair_color')
    op.drop_column('character', 'eye_color')
    # ### end Alembic commands ###
