"""empty message

Revision ID: 92c4f2781816
Revises: 77bcd95691d3
Create Date: 2021-04-13 21:05:00.437288

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '92c4f2781816'
down_revision = '77bcd95691d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character', sa.Column('birth_year', sa.String(length=25), nullable=True))
    op.add_column('character', sa.Column('mass', sa.Float(), nullable=True))
    op.drop_column('character', 'hair_color')
    op.add_column('planet', sa.Column('climate', sa.String(length=25), nullable=True))
    op.add_column('planet', sa.Column('diameter', sa.Integer(), nullable=True))
    op.add_column('planet', sa.Column('orbital_period', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('planet', 'orbital_period')
    op.drop_column('planet', 'diameter')
    op.drop_column('planet', 'climate')
    op.add_column('character', sa.Column('hair_color', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('character', 'mass')
    op.drop_column('character', 'birth_year')
    # ### end Alembic commands ###
