"""empty message

Revision ID: 9428fbb637ee
Revises: 230b19316e5a
Create Date: 2021-04-14 15:47:38.287588

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9428fbb637ee'
down_revision = '230b19316e5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('favorite', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorite', sa.Column('date', mysql.VARCHAR(length=25), nullable=True))
    # ### end Alembic commands ###
