"""empty message

Revision ID: cc9dd85de897
Revises: bc1c391212d1
Create Date: 2021-04-07 02:41:47.521189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc9dd85de897'
down_revision = 'bc1c391212d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('firstName', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('lastName', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('picture', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'picture')
    op.drop_column('user', 'lastName')
    op.drop_column('user', 'firstName')
    # ### end Alembic commands ###
